
version: '3'

services:

  configsrv1:
    container_name: configsrv1
    image: mongo
    command: mongod --configsvr --replSet rs0 --port 27017 --dbpath /data/db
    ports:
      - 27000:27017
    volumes:
      - configsrv1:/data/db

  configsrv2:
    container_name: configsrv2
    image: mongo
    command: mongod --configsvr --replSet rs0 --port 27017 --dbpath /data/db
    ports:
      - 27001:27017
    volumes:
      - configsrv2:/data/db

  configsrv3:
    container_name: configsrv3
    image: mongo
    command: mongod --configsvr --replSet rs0 --port 27017 --dbpath /data/db
    ports:
      - 27002:27017
    volumes:
      - configsrv3:/data/db

volumes:
  configsrv1: {}
  configsrv2: {}
  configsrv3: {}